### PR TITLE
Fix misspelling word separator

### PR DESCRIPTION
**Pull request by diego-antonelli**
There is a typo in the current parameter being received by the GH Action. Would be nice if this could be merged and fixed.

### CODE REVIEW

**Review by winterjung — APPROVED** [review]
thx for the contribution! I'll release it as v2 for backward compatibility.

**Comment by diego-antonelli** [comment]
@JungWinter can be a minor instead.. like 1.1

**Comment by winterjung** [comment]
@diego-antonelli If we bump the minor version, people who use split actions with just `@v1` versioning meet with broken changes. So I believe `v2` is more tolerance way :)

**Comment by diego-antonelli** [comment]
👍

**Pull request merged**
